"""initial schema

Revision ID: 95b306a6e3a8
Revises:
Create Date: 2026-09-02 20:33:56.706409
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - referenced by rendered JSONB(astext_type=...)

import curvevision.core.types  # noqa: F401 - referenced by rendered GUID() columns

from sqlalchemy.dialects import postgresql

revision: str = "95b306a6e3a8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_blobs",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("frame_rate", sa.Float(), nullable=True),
        sa.Column("thumbnail_key", sa.String(length=500), nullable=True),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_blobs")),
    )
    with op.batch_alter_table("media_blobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_blobs_sha256"), ["sha256"], unique=True)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "api_tokens",
        sa.Column("user_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("public_id", sa.String(length=32), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_tokens_public_id"), ["public_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("actor_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_actor_created", ["actor_id", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_resource_id"), ["resource_id"], unique=False
        )

    op.create_table(
        "background_tasks",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_background_tasks_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_tasks")),
        sa.UniqueConstraint("idempotency_key", name="uq_background_task_idempotency"),
    )
    with op.batch_alter_table("background_tasks", schema=None) as batch_op:
        batch_op.create_index("ix_background_task_state", ["state", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_background_tasks_resource_id"), ["resource_id"], unique=False
        )

    op.create_table(
        "organizations",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_organizations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "model_registrations",
        sa.Column("organization_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_labels",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_model_registrations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_registrations")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_model_slug"),
    )
    with op.batch_alter_table("model_registrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_registrations_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "organization_memberships",
        sa.Column("organization_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("user_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_org_membership"),
    )
    with op.batch_alter_table("organization_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_org_membership_user", ["user_id", "organization_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("organization_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("open_assignment", sa.Boolean(), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_project_slug"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projects_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "dataset_versions",
        sa.Column("project_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "statistics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_dataset_versions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_dataset_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("project_id", "name", name="uq_dataset_version_name"),
    )
    with op.batch_alter_table("dataset_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_versions_content_hash"), ["content_hash"], unique=False
        )

    op.create_table(
        "labels",
        sa.Column("project_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("parent_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "allowed_shape_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "skeleton_edges",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["labels.id"],
            name=op.f("fk_labels_parent_id_labels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_labels_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labels")),
        sa.UniqueConstraint("project_id", "name", "parent_id", name="uq_label_name"),
    )
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_labels_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_labels_project_id"), ["project_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("project_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("media_kind", sa.String(length=16), nullable=False),
        sa.Column("owner_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("assignee_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("segment_size", sa.Integer(), nullable=False),
        sa.Column("overlap", sa.Integer(), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tasks_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_tasks_owner_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tasks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_task_project_created", ["project_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_assignee_id"), ["assignee_id"], unique=False)

    op.create_table(
        "webhooks",
        sa.Column("organization_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("project_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("target_url", sa.String(length=1000), nullable=False),
        sa.Column("secret", sa.String(length=128), nullable=False),
        sa.Column(
            "events",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_webhooks_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhooks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_webhooks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhooks")),
    )
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhooks_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_webhooks_project_id"), ["project_id"], unique=False)

    op.create_table(
        "assets",
        sa.Column("task_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("blob_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["media_blobs.id"],
            name=op.f("fk_assets_blob_id_media_blobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_assets_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("task_id", "position", name="uq_asset_position"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index("ix_asset_task_position", ["task_id", "position"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_blob_id"), ["blob_id"], unique=False)

    op.create_table(
        "attribute_definitions",
        sa.Column("label_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("attribute_type", sa.String(length=20), nullable=False),
        sa.Column(
            "values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("default_value", sa.String(length=500), nullable=True),
        sa.Column("mutable", sa.Boolean(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["labels.id"],
            name=op.f("fk_attribute_definitions_label_id_labels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_definitions")),
        sa.UniqueConstraint("label_id", "name", name="uq_attribute_name"),
    )
    with op.batch_alter_table("attribute_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attribute_definitions_label_id"), ["label_id"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("task_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("stop_frame", sa.Integer(), nullable=False),
        sa.Column("assignee_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("reviewer_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("annotation_version", sa.Integer(), nullable=False),
        sa.Column("shape_count", sa.Integer(), nullable=False),
        sa.Column("track_count", sa.Integer(), nullable=False),
        sa.Column("tag_count", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_jobs_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_jobs_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_jobs_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("task_id", "index", name="uq_job_index"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_job_assignee_state", ["assignee_id", "state"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "media_chunks",
        sa.Column("task_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_media_chunks_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_chunks")),
        sa.UniqueConstraint("task_id", "index", "quality", name="uq_media_chunk"),
    )
    with op.batch_alter_table("media_chunks", schema=None) as batch_op:
        batch_op.create_index("ix_media_chunk_task", ["task_id", "index"], unique=False)

    op.create_table(
        "upload_sessions",
        sa.Column("task_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("declared_size", sa.BigInteger(), nullable=False),
        sa.Column("received_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_upload_sessions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_upload_sessions_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_sessions")),
    )
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_upload_sessions_task_id"), ["task_id"], unique=False)

    op.create_table(
        "webhook_deliveries",
        sa.Column("webhook_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
            name=op.f("fk_webhook_deliveries_webhook_id_webhooks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
    )
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_webhook_delivery_hook", ["webhook_id", "created_at"], unique=False
        )

    op.create_table(
        "annotation_events",
        sa.Column("job_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("actor_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("annotation_version", sa.Integer(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_annotation_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_annotation_events_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotation_events")),
    )
    with op.batch_alter_table("annotation_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_annotation_event_job_created", ["job_id", "created_at"], unique=False
        )

    op.create_table(
        "quality_reports",
        sa.Column("task_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("job_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("ground_truth_job_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("iou_threshold", sa.Float(), nullable=False),
        sa.Column("precision", sa.Float(), nullable=False),
        sa.Column("recall", sa.Float(), nullable=False),
        sa.Column("f1", sa.Float(), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ground_truth_job_id"],
            ["jobs.id"],
            name=op.f("fk_quality_reports_ground_truth_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_quality_reports_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_quality_reports_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_reports")),
    )
    with op.batch_alter_table("quality_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quality_reports_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quality_reports_task_id"), ["task_id"], unique=False)

    op.create_table(
        "shapes",
        sa.Column("job_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=False),
        sa.Column("shape_type", sa.String(length=24), nullable=False),
        sa.Column(
            "points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rotation", sa.Float(), nullable=False),
        sa.Column("occluded", sa.Boolean(), nullable=False),
        sa.Column("outside", sa.Boolean(), nullable=False),
        sa.Column("z_order", sa.Integer(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column(
            "mask",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "elements",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("label_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_shapes_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_shapes_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["label_id"], ["labels.id"], name=op.f("fk_shapes_label_id_labels"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shapes")),
        sa.UniqueConstraint("job_id", "client_id", name="uq_shape_client_id"),
    )
    with op.batch_alter_table("shapes", schema=None) as batch_op:
        batch_op.create_index("ix_shape_job_frame", ["job_id", "frame"], unique=False)
        batch_op.create_index("ix_shape_job_label", ["job_id", "label_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shapes_label_id"), ["label_id"], unique=False)

    op.create_table(
        "tags",
        sa.Column("job_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=True),
        sa.Column("label_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tags_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_tags_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["label_id"], ["labels.id"], name=op.f("fk_tags_label_id_labels"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("job_id", "client_id", name="uq_tag_client_id"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index("ix_tag_job_frame", ["job_id", "frame"], unique=False)
        batch_op.create_index(batch_op.f("ix_tags_label_id"), ["label_id"], unique=False)

    op.create_table(
        "tracks",
        sa.Column("job_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("shape_type", sa.String(length=24), nullable=False),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("label_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tracks_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_tracks_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["label_id"], ["labels.id"], name=op.f("fk_tracks_label_id_labels"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracks")),
        sa.UniqueConstraint("job_id", "client_id", name="uq_track_client_id"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index("ix_track_job", ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_label_id"), ["label_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_object_id"), ["object_id"], unique=False)

    op.create_table(
        "issues",
        sa.Column("job_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=False),
        sa.Column(
            "position",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("shape_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("track_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("resolved_by_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_issues_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_issues_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_issues_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shape_id"], ["shapes.id"], name=op.f("fk_issues_shape_id_shapes"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_issues_track_id_tracks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index("ix_issue_job_state", ["job_id", "state"], unique=False)

    op.create_table(
        "track_shapes",
        sa.Column("track_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=False),
        sa.Column(
            "points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rotation", sa.Float(), nullable=False),
        sa.Column("occluded", sa.Boolean(), nullable=False),
        sa.Column("outside", sa.Boolean(), nullable=False),
        sa.Column("keyframe", sa.Boolean(), nullable=False),
        sa.Column("z_order", sa.Integer(), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "mask",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "elements",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("fk_track_shapes_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_shapes")),
        sa.UniqueConstraint("track_id", "frame", name="uq_track_shape_frame"),
    )
    with op.batch_alter_table("track_shapes", schema=None) as batch_op:
        batch_op.create_index("ix_track_shape_track_frame", ["track_id", "frame"], unique=False)

    op.create_table(
        "comments",
        sa.Column("issue_id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("author_id", curvevision.core.types.GUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", curvevision.core.types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_comments_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_issue_id"), ["issue_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_issue_id"))

    op.drop_table("comments")
    with op.batch_alter_table("track_shapes", schema=None) as batch_op:
        batch_op.drop_index("ix_track_shape_track_frame")

    op.drop_table("track_shapes")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index("ix_issue_job_state")

    op.drop_table("issues")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_object_id"))
        batch_op.drop_index(batch_op.f("ix_tracks_label_id"))
        batch_op.drop_index("ix_track_job")

    op.drop_table("tracks")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_label_id"))
        batch_op.drop_index("ix_tag_job_frame")

    op.drop_table("tags")
    with op.batch_alter_table("shapes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shapes_label_id"))
        batch_op.drop_index("ix_shape_job_label")
        batch_op.drop_index("ix_shape_job_frame")

    op.drop_table("shapes")
    with op.batch_alter_table("quality_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_reports_task_id"))
        batch_op.drop_index(batch_op.f("ix_quality_reports_job_id"))

    op.drop_table("quality_reports")
    with op.batch_alter_table("annotation_events", schema=None) as batch_op:
        batch_op.drop_index("ix_annotation_event_job_created")

    op.drop_table("annotation_events")
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.drop_index("ix_webhook_delivery_hook")

    op.drop_table("webhook_deliveries")
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_upload_sessions_task_id"))

    op.drop_table("upload_sessions")
    with op.batch_alter_table("media_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_media_chunk_task")

    op.drop_table("media_chunks")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_task_id"))
        batch_op.drop_index("ix_job_assignee_state")

    op.drop_table("jobs")
    with op.batch_alter_table("attribute_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attribute_definitions_label_id"))

    op.drop_table("attribute_definitions")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_blob_id"))
        batch_op.drop_index("ix_asset_task_position")

    op.drop_table("assets")
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhooks_project_id"))
        batch_op.drop_index(batch_op.f("ix_webhooks_organization_id"))

    op.drop_table("webhooks")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_assignee_id"))
        batch_op.drop_index("ix_task_project_created")

    op.drop_table("tasks")
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_labels_project_id"))
        batch_op.drop_index(batch_op.f("ix_labels_parent_id"))

    op.drop_table("labels")
    with op.batch_alter_table("dataset_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_versions_content_hash"))

    op.drop_table("dataset_versions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_organization_id"))

    op.drop_table("projects")
    with op.batch_alter_table("organization_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_org_membership_user")

    op.drop_table("organization_memberships")
    with op.batch_alter_table("model_registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_registrations_organization_id"))

    op.drop_table("model_registrations")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))

    op.drop_table("organizations")
    with op.batch_alter_table("background_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_background_tasks_resource_id"))
        batch_op.drop_index("ix_background_task_state")

    op.drop_table("background_tasks")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_resource_id"))
        batch_op.drop_index("ix_audit_actor_created")

    op.drop_table("audit_events")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_tokens_public_id"))

    op.drop_table("api_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("media_blobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_blobs_sha256"))

    op.drop_table("media_blobs")
    # ### end Alembic commands ###
