#!/usr/bin/env python3
"""Generate `web/src/api/schema.ts` from the server's own OpenAPI document, or check it.

    python scripts/api_types.py           # regenerate
    python scripts/api_types.py --check   # fail if it no longer matches the server

`web/src/api/types.ts` is written by hand and was checked against nothing, so a field the
server renamed or dropped showed up only as a value that was quietly `undefined`. This
writes what the server actually declares, and `web/src/api/__tests__/contract.ts` holds the
hand-written interfaces to it at compile time. The document is built from the app itself —
no server is started and no database is touched.

Run it after changing a Pydantic schema the web client reads; `./scripts/check.sh` runs the
check.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
OUTPUT = WEB / "src" / "api" / "schema.ts"


def openapi_document() -> dict[str, object]:
    sys.path.insert(0, str(ROOT / "server"))
    from curvevision.core.config import Settings
    from curvevision.main import create_app

    settings = Settings(
        environment="test",
        secret_key="schema-export-only-never-used-to-sign-anything",
        database_url="sqlite+aiosqlite:///:memory:",
        storage_backend="local",
        storage_local_root=tempfile.gettempdir(),
        job_queue_backend="inline",
        log_level="WARNING",
    )
    return create_app(settings).openapi()


def generate() -> str:
    with tempfile.TemporaryDirectory() as workspace:
        document = Path(workspace) / "openapi.json"
        target = Path(workspace) / "schema.ts"
        document.write_text(json.dumps(openapi_document(), indent=2, sort_keys=True))
        subprocess.run(
            ["npx", "--no-install", "openapi-typescript", str(document), "-o", str(target)],
            cwd=WEB,
            check=True,
            capture_output=True,
        )
        header = (
            "// Generated by scripts/api_types.py from the server's OpenAPI document.\n"
            "// Do not edit: change the Pydantic schema and run the script.\n"
        )
        return header + target.read_text()


def main() -> int:
    generated = generate()
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            print(
                f"{OUTPUT.relative_to(ROOT)} does not match the server's schema.\n"
                "Run: python scripts/api_types.py, and update web/src/api/types.ts if the\n"
                "contract check then fails."
            )
            return 1
        print("api types match the server")
        return 0
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
